### ISSUE TITLE
Core dump when running on OSX

### ISSUE THREAD

**Issue by lmilbaum** [ifireball/review_wof#5]
```
flask.cli.NoAppException
flask.cli.NoAppException: While importing "review_wof", an ImportError was raised:

Traceback (most recent call last):
  File "/Users/liora/.local/share/virtualenvs/review_wof-j7V4NJSq/lib/python3.6/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/Users/liora/src/github.com/lioramilbaum/review_wof/review_wof/__init__.py", line 6, in <module>
    from .model import patches_view
  File "/Users/liora/src/github.com/lioramilbaum/review_wof/review_wof/model/patches_view.py", line 3, in <module>
    from pandas import DataFrame
ModuleNotFoundError: No module named 'pandas'

Traceback (most recent call last)
File "/Users/liora/src/github.com/lioramilbaum/review_wof/review_wof/__init__.py", line 6, in <module>
from .model import patches_view
File "/Users/liora/src/github.com/lioramilbaum/review_wof/review_wof/model/patches_view.py", line 3, in <module>
from pandas import DataFrame
During handling of the above exception, another exception occurred:
File "/Users/liora/.local/share/virtualenvs/review_wof-j7V4NJSq/lib/python3.6/site-packages/flask/cli.py", line 338, in __call__
self._flush_bg_loading_exception()
File "/Users/liora/.local/share/virtualenvs/review_wof-j7V4NJSq/lib/python3.6/site-packages/flask/cli.py", line 326, in _flush_bg_loading_exception
reraise(*exc_info)
File "/Users/liora/.local/share/virtualenvs/review_wof-j7V4NJSq/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
raise value
File "/Users/liora/.local/share/virtualenvs/review_wof-j7V4NJSq/lib/python3.6/site-packages/flask/cli.py", line 314, in _load_app
self._load_unlocked()
File "/Users/liora/.local/share/virtualenvs/review_wof-j7V4NJSq/lib/python3.6/site-packages/flask/cli.py", line 330, in _load_unlocked
self._app = rv = self.loader()
File "/Users/liora/.local/share/virtualenvs/review_wof-j7V4NJSq/lib/python3.6/site-packages/flask/cli.py", line 388, in load_app
app = locate_app(self, import_name, name)
File "/Users/liora/.local/share/virtualenvs/review_wof-j7V4NJSq/lib/python3.6/site-packages/flask/cli.py", line 247, in locate_app
"\n\n{tb}".format(name=module_name, tb=traceback.format_exc())
flask.cli.NoAppException: While importing "review_wof", an ImportError was raised:

Traceback (most recent call last):
File "/Users/liora/.local/share/virtualenvs/review_wof-j7V4NJSq/lib/python3.6/site-packages/flask/cli.py", line 240, in locate_app
__import__(module_name)
File "/Users/liora/src/github.com/lioramilbaum/review_wof/review_wof/__init__.py", line 6, in <module>
from .model import patches_view
File "/Users/liora/src/github.com/lioramilbaum/review_wof/review_wof/model/patches_view.py", line 3, in <module>
from pandas import DataFrame
ModuleNotFoundError: No module named 'pandas'
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
```

**Comment by lmilbaum** [comment]
setup.py didn't install pandas
